# Generated by Django 5.1.3 on 2025-04-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('consult', models.IntegerField(choices=[(0, 'consulta'), (1, 'reclamo'), (2, 'Sugerencias')])),
                ('message', models.TextField()),
                ('notices', models.BooleanField()),
            ],
        ),
    ]
